#!/usr/bin/env bash

set -euo pipefail

DOCKER_IMAGE="node-tc"

ROOT="$(git rev-parse --show-toplevel)"

imageBuild() {
    docker build --tag ${DOCKER_IMAGE} --file "${ROOT}/Dockerfile" "${ROOT}"
}

startServerWithNode(){
    docker-compose -f docker-compose.yml -p ui_test_demo up -d --remove-orphans > results/logs/docker-compose.log
}

testRun() {
    docker run --name $1 ${DOCKER_IMAGE} mvn clean install -Dcucumber.options="--tags @MQA-101" -q
}

copyReportsToJenkins() {
    sourceLocation=$1':/app/target/cucumber-report-html/cucumber-html-reports/.'
    destinationLocation='.'$2
    docker cp $sourceLocation $destinationLocation
}

stopServerAndNode(){
    docker-compose -p ui_test_demo down --remove-orphans
}

removeContainer() {
    docker rm $1
}

removeImage() {
    docker rmi ${DOCKER_IMAGE} -f
}
"$@"